In [1]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)

[36, 42, 38, 33, 64]


In [2]:
symbols = "$*&!@"

codes = [ord(symbol) for symbol in symbols]
print(codes)

[36, 42, 38, 33, 64]


In [3]:
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [4]:
symbols = '"!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [5]:
symbols = '"!~$$*&!@'
beyond_ascii = list(filter(lambda c: c > 64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")


[126] 

Map function:
>>> <map object at 0x00000210FEF877C0>
List after map:
>>> [34, 33, 126, 36, 36, 42, 38, 33, 64]


In [6]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [9]:
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [10]:
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [11]:
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [12]:
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [13]:
for contury, _ in traveler_ids:
    print(contury)

USA
BRA
ESP


In [14]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
print('%s %s' % passport)

USA 31195855


In [16]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [18]:
a = 10; b = 20
b,a = a,b
print(a,b)

20 10


In [19]:
divmod(20,8)

(2, 4)

In [20]:
t = (20,8)
divmod(*t)

(2, 4)

In [21]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [23]:
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [24]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [26]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [27]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [28]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [29]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [30]:
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833))]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


In [31]:
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))

In [32]:
tokyo.population

36.933

In [33]:
tokyo.coordinates

(35.689722, 139.691667)

In [34]:
tokyo[1]

'JP'

In [35]:
City._fields

('name', 'country', 'population', 'coordinates')

In [36]:
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889))

In [37]:
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613889, long=77.208889)}

In [38]:
for key, value in delhi._asdict().items():
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


In [39]:
l = [10, 20, 30, 40, 50, 60]
l[:2]

[10, 20]

In [40]:
l[2:]

[30, 40, 50, 60]

In [41]:
l[:3]

[10, 20, 30]

In [42]:
l[3:]

[40, 50, 60]

In [43]:
invoice = """
0.....6..................25.......33......40.......
1909  Pimoroni             $17.50    3    $52.50
1489  6mm Tactile          $4.95     2    $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

  $17.50 Pimoroni           
  $4.95  6mm Tactile        
 


In [59]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [60]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [61]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [62]:
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [63]:
l[2:5] = 100

TypeError: can only assign an iterable

In [64]:
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [65]:
l = [1, 2 ,3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [66]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [67]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [68]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [69]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [70]:
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [71]:
row = ['_'] * 3
board = []
for i in range(3):
  board.append(row)

board[1][2] = 'X'

board

[['_', '_', 'X'], ['_', '_', 'X'], ['_', '_', 'X']]

In [72]:
board = []
for i in range(3):
  row = ['_'] * 3
  board.append(row)

print(board)

board[2][0] = 'X'

board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [73]:
l = [1,2,3]
id(l)

2269921529792

In [74]:
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [75]:
id(l)

2269921529792

In [76]:
t = (1,2,3)
id(t)

2272025872704

In [77]:
t *= 2
id(t)

2269920153888

In [1]:
t = (1, 2, [30, 40])
print(t)


t[2] += [50, 60]

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [79]:
print(t)

(1, 2, [30, 40, 50, 60])


In [80]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(fruits)

['grape', 'raspberry', 'apple', 'banana']


In [81]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [82]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [83]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [84]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [85]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [86]:
fruits.sort()
fruits

['apple', 'banana', 'grape', 'raspberry']

In [87]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.9272913099016558

In [88]:
with open('floats.bin', 'wb') as f:
  floats.tofile(f)

In [89]:
floats2 = array('d')

with open('floats.bin', 'rb') as f:
  floats2.fromfile(f, 10**7)

floats2[-1]

0.9272913099016558

In [90]:
floats == floats2

True

In [91]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [92]:
memv[0]

-2

In [93]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [94]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [95]:
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
type(a)

numpy.ndarray

In [97]:
a.shape

(12,)

In [98]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
a[2]

array([ 8,  9, 10, 11])

In [100]:
a[2, 1]

9

In [101]:
a[:, 1]

array([1, 5, 9])

In [102]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [103]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [104]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [105]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [106]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [107]:
dq.extend([11, 22, 33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [108]:
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)